### PR TITLE
Currency update fix

### PR DESCRIPTION
**Pull request by raiwa**

### CODE REVIEW

**Comment by raiwa** [comment]
Please have a look on the language definition in currency.php and the text in config entries. I'm not native :-)

**Comment by BrockleyJohn** [comment]
so was oanda the only one that was working?

**Comment by raiwa** [comment]
As far as I know, the only one which was working with the existing code until a few days ago was fixer.
fixer requires now to register and a code update to use the provided access key.
Now this code change for xe has been posted to make it work again:
[https://forums.oscommerce.com/topic/412996-updating-currencies-with-fixer-not-working-anymore/?do=findComment&comment=1771375](url)

Maybe oanda should be complete removed as it seems it does not work any more at all.

**Comment by raiwa** [comment]
Just checked. OANDA has only a 30 days free trial. Otherwise pricing starts with 400$/month => not interesting for OsC users I guess.

**Comment by BrockleyJohn** [comment]
ok, but maybe there's enough to do without changing things we don't have to!

**Pull request merged**
